create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  count integer not null check (count between 1 and 10),
  tickets jsonb not null
);
